// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig, env } from "prisma/config";
import { config } from "dotenv";

// Manually trigger dotenv to ensure process.env is populated 
// before the defineConfig object is exported
config(); 

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'pnpm dlx tsx prisma/seed.ts',
  },
  datasource: {
    // Now this will resolve correctly
    url: env("DATABASE_URL"),
  },
});
